name: "Deploy to VPS"
on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    name: Deploy on self-hosted runner
    runs-on: [self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run deploy script
        run: |
          chmod +x ./deploy.sh
          ./deploy.sh